### ISSUE TITLE
Could the discussions tab be opened for non questions/bugs?

### ISSUE THREAD

**Issue by kleenkanteen** [machinescream/bolter#2]
This place may not be the best place. I was wondering how does this package differ from the standard Provider package and Riverpod? Would like to see an extensive explanation as a beginner.

**Comment by machinescream** [comment]
Hi, please read readme. This package saves hours and days of heavy work for me. Try and tell how it's going =)

**Comment by kleenkanteen** [comment]
@machinescream The readme does not explainthe difference between the standard Provider package and Riverpod.

**Comment by machinescream** [comment]
> @machinescream The readme does not explainthe difference between the standard Provider package and Riverpod.

And why should it?

**Comment by kleenkanteen** [comment]
@machinescream Don't know why you are being defensive....I am merely trying to know the practical differences between them without having to use all of them extensively.
